### ISSUE TITLE
Powder_snow bucket Bug

### ISSUE THREAD

**Issue by Scinestro** [Roundaround/mc-fabric-stackables#13] opened 2023-10-08 15:01 UTC
Version 1.3.1 has a bug with powder snow buckets , when you place them consecutively twice, the second time you attempt to place it, your bucket disappears, without any changes to the mod configurations.

**Comment by Rozbiynk** [comment] 2023-12-30 11:39
bump

**Comment by Roundaround** [comment] 2024-01-05 16:46
Unfortunately I can't reproduce this. When I try to place powdered snow onto the ground it works as expected, and trying to place it into a cauldron consumes the snow bucket (as happens in vanilla), but still gives me back the empty bucket. If my inventory is full, it tosses the bucket on the ground.

Can you be more specific about what's happening for you? If possible, could you provide a screen recording, or at least a detailed list of steps?

**Comment by mintynoura** [comment] 2024-01-06 15:12
tested on 1.20.1

https://github.com/Roundaround/mc-fabric-stackables/assets/107040228/0a748469-34bd-41f6-923a-4d654b433a24

it deletes your bucket when you place it on the ground. in cauldrons it still works fine

**Comment by Roundaround** [comment] 2024-01-06 16:12
Aha! Okay I found the issue. It'll be fixed in the next minor version (2.0.1) but I'm going to wait until I've backported 2.0.0+ to the previous Minecraft versions before I release it. Please be patient and thank you for the video!

**Comment by mintynoura** [comment] 2024-01-06 16:15
don’t worry at all, thank you for your hard work on this amazing mod!

**Comment by Roundaround** [comment] 2024-01-06 16:57
Turns out it was easier to port the updates back to 1.20 than I thought. 2.0.1 is released for all versions of Minecraft 1.20.X on Modrinth with the fix for this! :)

**Closed by Roundaround** 2024-01-06 16:57 UTC
