### ISSUE TITLE
Can't rename stacks of items

### ISSUE THREAD

**Issue by tesseract-two** [Roundaround/mc-fabric-stackables#17] opened 2023-11-07 00:25 UTC
With this mod installed and default settings, I cannot rename stacks of items at once, only a single item. However, it still consumes experience when attempting to rename stacks.

Setup:
Minecraft 1.20.1
No Telemetry 1.7.0
Stackables 1.3.1

Minecraft 1.20.2
No Telemetry 1.7.0
Stackables 1.4.0

Steps to reproduce:
1. Try to rename a full stack of items in an anvil
2. Notice that you cannot rename a stack and it still cost experience

**Comment by Roundaround** [comment] 2024-01-05 16:26
Duplicate of #21

**Comment by Roundaround** [comment] 2024-01-05 16:27
Duplicate of #21

**Closed** 2024-01-05 16:27 UTC
